## Deployment playbook goes here.
# create web directory for my wep_server
- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: git the app
  ansible.builtin.git:
    repo: "https://github.com/hossamalsankary/cdond-c3-project_3.git"
    dest: ~/web
    version: release-0.22

- name: Executing node
  shell: |
    pm2 start ~/web/backend/src/main.ts
