---
- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Extract foo.tgz into /var/lib/foo
  unarchive:
    src: "tarartifact.tar.gz"
    dest: "~/web"

- name: Executing node
  shell: |
    cd ~/web
    printenv > .env
    npm install
    pm2 stop default
    pm2 start npm -- start
