---
- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Extract foo.tgz into /var/lib/foo
  unarchive:
    src: artifact.tar.gz
    dest: ~/web

- name: Executing node
  shell: |
    cd ~/web/backend
    echo ENVIRONMENT=production > .env
    echo TYPEORM_CONNECTION=postgres >> .env
    echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> .env
    echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> .env
    echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> .env
    echo NODE_ENV=production >> .env
    echo TYPEORM_HOST=$TYPEORM_HOST >> .env
    echo TYPEORM_PORT=$TYPEORM_PORT >> .env
    echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> .env
    echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> .env
    echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> .env
    npm install
    pm2 stop default
    pm2 start npm -- start
