---
- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Extract foo.tgz into /var/lib/foo
  unarchive:
    src: artifact.tar.gz
    dest: ~/web

- name: Executing node
  shell: |
    cd ~/web/backend
    ls
    npm install
     pm2 stop default
     pm2 start npm -- start
